call D:\GreatCowBASICGits\DATFileGenerator.git\trunk\XC8toINC_Converters\PIC18\PICJ94Series\j94 18F65J94
pause
call D:\GreatCowBASICGits\DATFileGenerator.git\trunk\XC8toINC_Converters\PIC18\PICJ94Series\j94 18F66J94
call D:\GreatCowBASICGits\DATFileGenerator.git\trunk\XC8toINC_Converters\PIC18\PICJ94Series\j94 18F85J94
call D:\GreatCowBASICGits\DATFileGenerator.git\trunk\XC8toINC_Converters\PIC18\PICJ94Series\j94 18F86J94
call D:\GreatCowBASICGits\DATFileGenerator.git\trunk\XC8toINC_Converters\PIC18\PICJ94Series\j94 18F95J94
call D:\GreatCowBASICGits\DATFileGenerator.git\trunk\XC8toINC_Converters\PIC18\PICJ94Series\j94 18F96J94



