call D:\DAT\XC8toINC_Converters\PIC18\PIC18Qseries\Q84 18F27Q83

call D:\DAT\XC8toINC_Converters\PIC18\PIC18Qseries\Q84 18F26Q83

call D:\DAT\XC8toINC_Converters\PIC18\PIC18Qseries\Q84 18F46Q83
call D:\DAT\XC8toINC_Converters\PIC18\PIC18Qseries\Q84 18F47Q83
call D:\DAT\XC8toINC_Converters\PIC18\PIC18Qseries\Q84 18F56Q83
call D:\DAT\XC8toINC_Converters\PIC18\PIC18Qseries\Q84 18F57Q83



